### ISSUE TITLE
installs non-async-signal-safe code as raw `sigaction` handler --> undefined behaviour, might deadlock/crash

### ISSUE THREAD

**Issue by weissi** [iCharlesHu/swift-experimental-subprocess#8]
https://github.com/iCharlesHu/swift-experimental-subprocess/blob/d3ce2658827c1381638563337ee24cf0c09440ef/Sources/Subprocess/Platforms/Subprocess%2BLinux.swift#L223-L244

Async signal safety is tricky in UNIX, a programmer must be sure to only call a very limited set of documented functions (see https://man7.org/linux/man-pages/man7/signal-safety.7.html). Particularly bad is to allocate memory, run callback code or take locks in signal handlers. This package does all of those.

The problem is that the signal handler may be running on a stack that's currently in libc's malloc function or inside another function with a lock already held.

**Comment by iCharlesHu** [comment]
We should use `DispatchSource.makeSignalSource` instead.
